# Generated by Django 5.2.5 on 2025-09-26 06:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(blank=True, max_length=30, verbose_name='项目编号')),
                ('project_name', models.CharField(blank=True, max_length=50, verbose_name='项目名称')),
                ('customer_name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('customer_address', models.CharField(max_length=200, verbose_name='客户地址')),
                ('customer_contact', models.CharField(max_length=100, verbose_name='客户联系人')),
                ('customer_phone', models.CharField(max_length=11, verbose_name='客户联系方式')),
                ('project_amount', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='项目金额')),
                ('required_start', models.DateField(verbose_name='要求开始时间')),
                ('required_end', models.DateField(verbose_name='要求结束时间')),
                ('actual_start', models.DateField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='实际结束时间')),
                ('status', models.CharField(choices=[('未开发', '未开发'), ('开发中', '开发中'), ('已完成', '已完成'), ('已验收', '已验收')], default='未开发', max_length=20, verbose_name='项目状态')),
                ('business_owner', models.CharField(max_length=100, verbose_name='项目商务负责人')),
                ('implementation_owner', models.CharField(max_length=100, verbose_name='项目实施负责人')),
                ('developers', models.TextField(verbose_name='项目开发人员')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='项目创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=20, verbose_name='阶段')),
                ('total_work_time', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='总工作时间')),
                ('total_vacation_time', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='总休假时间')),
                ('total_overtime', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='总加班时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects', verbose_name='项目')),
            ],
            options={
                'verbose_name': '日志主表',
                'verbose_name_plural': '日志主表',
                'db_table': 'api_log',
            },
        ),
        migrations.CreateModel(
            name='LogsDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('work_time', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, verbose_name='工作时间')),
                ('work_type', models.CharField(choices=[('正常工时', '正常工时'), ('加班工时', '加班工时'), ('休假工时', '休假工时')], default='正常工时', max_length=10, verbose_name='工作类型')),
                ('work_description', models.TextField(blank=True, verbose_name='工作描述')),
                ('log_status', models.CharField(choices=[('已保存', '已保存'), ('已提交', '已提交'), ('已通过', '已通过'), ('未通过', '未通过')], default='已保存', max_length=10, verbose_name='日志状态')),
                ('save_time', models.DateTimeField(blank=True, null=True, verbose_name='保存时间')),
                ('submit_time', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('check_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('fail_cause', models.CharField(blank=True, max_length=100, null=True, verbose_name='未通过原因')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_dates', to='api.logs', verbose_name='关联日志')),
            ],
            options={
                'verbose_name': '日志日期信息表',
                'verbose_name_plural': '日志日期信息表',
                'db_table': 'api_log_date',
            },
        ),
        migrations.CreateModel(
            name='ProjectPhases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=100, verbose_name='阶段名称')),
                ('phase_order', models.IntegerField(default=0, verbose_name='阶段顺序')),
                ('phase_start', models.DateField(blank=True, null=True, verbose_name='阶段开始时间')),
                ('phase_end', models.DateField(blank=True, null=True, verbose_name='阶段结束时间')),
                ('phase_description', models.TextField(blank=True, null=True, verbose_name='阶段描述')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.projects', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目阶段',
                'verbose_name_plural': '项目阶段',
                'ordering': ['phase_order'],
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=100, verbose_name='报告标题')),
                ('report_author', models.CharField(default='', max_length=100, verbose_name='报告作者')),
                ('report_date', models.DateField(verbose_name='报告日期')),
                ('report_content', models.TextField(verbose_name='报告内容')),
                ('plan', models.TextField(verbose_name='下周工作计划')),
                ('issues', models.TextField(blank=True, null=True, verbose_name='遇到的问题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.projects', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '周报',
                'verbose_name_plural': '周报',
            },
        ),
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='手机号码')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('staff_type', models.CharField(blank=True, choices=[('管理人员', '管理人员'), ('实施人员', '实施人员')], max_length=100, verbose_name='员工类型')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('status', models.CharField(blank=True, choices=[('正常', '正常'), ('忙碌', '忙碌'), ('离线', '离线'), ('禁用', '禁用')], max_length=100, verbose_name='状态')),
                ('avatar', models.CharField(default='头像', max_length=10, verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UsersInfo', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
    ]
