# Generated by Django 5.2.5 on 2025-09-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='customer_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='客户地址'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='客户联系人'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='客户联系方式'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, verbose_name='项目金额'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(max_length=50, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_number',
            field=models.CharField(max_length=30, verbose_name='项目编号'),
        ),
    ]
