# Generated by Django 5.2.5 on 2025-09-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_projects_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='developers',
            field=models.TextField(blank=True, null=True, verbose_name='项目开发人员'),
        ),
    ]
