# Generated by Django 5.2.5 on 2025-10-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_projects_developers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsdate',
            name='log_status',
            field=models.CharField(choices=[('未保存', '未保存'), ('已保存', '已保存'), ('已提交', '已提交'), ('已通过', '已通过'), ('未通过', '未通过')], default='已保存', max_length=10, verbose_name='日志状态'),
        ),
    ]
