# Generated by Django 5.2.5 on 2025-10-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_logsdate_log_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='total_overtime',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='total_vacation_time',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='total_work_time',
        ),
    ]
